db:
  build: ./db
  dockerfile: Dockerfile
  environment:
    MYSQL_ROOT_PASSWORD: "Password"
  ports:
    - "3306:3306"
app:
  image: malikashish8/vuln-spring
  environment:
      RAILS_ENV: development
  links:
      - db
  ports:
    - "8082:8082"
